In [1]:
import numpy as np

## 1. 1차원 배열

In [4]:
a1 = [1, 2, 3, 4, 5, 10, 20, "가", "나"]
print(type(a1))
print(a1)

<class 'list'>
[1, 2, 3, 4, 5, 10, 20, '가', '나']


In [9]:
a2 = np.array([1, 2, 3, 4, 5, 10, 20, "가", "나"])
print(a2)
print(type(a2))
print(a2.shape)
print(a2.dtype)

['1' '2' '3' '4' '5' '10' '20' '가' '나']
<class 'numpy.ndarray'>
(9,)
<U11


In [12]:
# a3 = np.array([1, 2, 3, 4, 5, 10, 20], dtype=float)
a3 = np.array([1, 2, 3, 4, 5, 10, 20], float)
print(a3)
print(a3.dtype)

[ 1.  2.  3.  4.  5. 10. 20.]
float64


In [13]:
##### 백터화 연산
data1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

print(data1 * 3)
# print(data1 - 3)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [15]:
dataArray = np.array(data1)

print(dataArray * 3)
print(dataArray + 3)
print(dataArray - 3)

[ 0  3  6  9 12 15 18 21 24 27]
[ 3  4  5  6  7  8  9 10 11 12]
[-3 -2 -1  0  1  2  3  4  5  6]


In [16]:
##### 인덱스 접근
print(dataArray[0], dataArray[1])

0 1


## 2. 2차원 배열

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr[0])
print(arr[0][0])
print(arr.shape)

[[1 2 3]
 [4 5 6]]
[1 2 3]
1
(2, 3)


## 3. 3차원 배열

In [29]:
arr3 = np.array([ [[1, 2, 3, 4], [3, 4, 5, 6]], 
                 [[7, 8, 9, 10], [11, 12, 13, 14]]])
print(arr3)
print("-------------------")
print(arr3[0])
print("-------------------")
print(arr3[0][0])
print("-------------------")
print(arr3[0][0][0])
print("-------------------")
print(arr3.shape)
print("-------------------")
print(arr3.ndim)
print("-------------------")
print(len(arr3), len(arr3[0]), len(arr3[0][0]))

[[[ 1  2  3  4]
  [ 3  4  5  6]]

 [[ 7  8  9 10]
  [11 12 13 14]]]
-------------------
[[1 2 3 4]
 [3 4 5 6]]
-------------------
[1 2 3 4]
-------------------
1
-------------------
(2, 2, 4)
-------------------
3
-------------------
2 2 4


## 4. 집계 함수

In [31]:
x = np.random.randn(8)
y = np.random.randn(8)
print(x)
print(y)

[ 0.51650938  0.13616712 -0.64380494  2.6165685  -1.12900909 -1.25412064
 -2.35866487 -1.65834393]
[-1.43924151  0.94063271  0.76619557  0.67897437  1.04743236 -0.47866428
 -1.01344463  0.54517999]


In [34]:
print(np.maximum(x, y))

[ 0.51650938  0.94063271  0.76619557  2.6165685   1.04743236 -0.47866428
 -1.01344463  0.54517999]


In [33]:
arr = np.random.randn(5, 4)
print(arr)

[[ 1.94804017  0.04501867 -0.92761459  1.87022601]
 [ 0.5475628  -1.19590441 -0.97396971 -0.38916051]
 [ 0.40298474 -1.28657254 -1.4342758  -2.14292873]
 [ 0.16891251  0.27631117  0.99793658 -1.71732216]
 [-0.74699225  0.57222559 -0.58073034 -0.83872755]]


In [36]:
print(arr.sum())
print(arr.sum(axis=0))  # 열의 합계
print(arr.sum(axis=1))  # 행의 합계

-5.404980356624963
[ 2.32050798 -1.58892152 -2.91865387 -3.21791294]
[ 2.93567027 -2.01147184 -4.46079233 -0.27416191 -1.59422455]


## 5. 배열의 인덱싱

In [37]:
arr = np.array([100, 200, 300, 400, 500])

print(arr[2], arr[4], arr[-1], arr[-3])

300 500 500 300


In [41]:
arr = np.array([[0, 1, 2], [3, 4, 5]])

temp = [[0, 1, 2], [3, 4, 5]]
print(temp[0][1])

print(arr[0][1], arr[0, 1], arr[-1, -1])

1
1 1 5


In [54]:
##### fancy index

arr = np.array([i for i in range(10)])
print(arr)
idx = np.array([True, False, True, False, True, False, True, False, True, False])

print(arr[idx])

print(arr[arr % 2 == 0])

# arr에서 3의 배수를 찾아라
print(arr[arr % 3 == 0])

# arr에서 4로 나누면 1이 남는 수를 찾아라
print(arr[arr % 4 == 1])

# arr에서 3으로 나누면 나눠지고 4로 나누면 1이 남는 수를 찾아라
temp_arr = arr[arr % 3 == 0]
result = temp_arr[temp_arr % 4 == 1]
print(result)

print(arr[(arr % 3 == 0) & (arr % 4 == 1)] )


[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 2 4 6 8]
[0 3 6 9]
[1 5 9]
[9]
[9]


## 6. 배열의 슬라이싱

In [60]:
arr = np.array([[0, 1, 2, 3], 
                [4, 5, 6, 7],
                [8, 9, 10, 11]])

print(arr)
print("------------------------")
print(arr[0, 0:2])
print("------------------------")
print(arr[1:3, 0:2])
print("------------------------")
print(arr[0, :])
print("------------------------")
print(arr[[2, 1, 0], :])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
------------------------
[0 1]
------------------------
[[4 5]
 [8 9]]
------------------------
[0 1 2 3]
------------------------
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


## 7. numpy 자료형

+ b : 불리언
+ i : 정수형
+ u : 부호없는 정수형
+ f : 부동 소수점(실수형)
+ c : 복소수
+ O : 객체
+ S : 바이트 문자열
+ U : 유니코드 문자열

In [62]:
# a1 = np.dtype("i")
a1 = np.dtype("i8")
print(a1)

int64


In [67]:
# arr = np.array([1, 2, 3], dtype="f")
arr = np.array([1, 2, 3], dtype=np.float16)

print(arr.dtype)
print(arr[0] + arr[1])

print("-----------------------------------")

arr = np.array([1, 2, 3], dtype="U")
print(arr.dtype)
print(arr[0] + arr[1])

float16
3.0
-----------------------------------
<U1
12


## 8. 배열 생성

In [73]:
arr = np.zeros(5)
print(arr)
print(arr.dtype)
print(type(arr))

print("-----------------------------------")

arr = np.zeros(5, dtype="i8")
print(arr)
print(arr.dtype)

print("-----------------------------------")

arr = np.zeros(5, dtype="U4")
print(arr)
print(arr.dtype)

arr[0] = "abc"
arr[1] = "abcd"
arr[2] = "abcde"  # 4글자로 한정하여 e는 표현되지 않음

print(arr)

print("-----------------------------------")

arr = np.zeros(5, dtype="S4")
print(arr)
print(arr.dtype)

arr[0] = "abc"
arr[1] = "abcd"
arr[2] = "abcde"

print(arr)

print("-----------------------------------")


print(np.zeros((2, 3)))

[0. 0. 0. 0. 0.]
float64
<class 'numpy.ndarray'>
-----------------------------------
[0 0 0 0 0]
int64
-----------------------------------
['' '' '' '' '']
<U4
['abc' 'abcd' 'abcd' '' '']
-----------------------------------
[b'' b'' b'' b'' b'']
|S4
[b'abc' b'abcd' b'abcd' b'' b'']
-----------------------------------
[[0. 0. 0.]
 [0. 0. 0.]]


## 9. 전치

## 10. 크기변경

## 11. 배열 연결(병합) 
+ hstack, vstack, dstack, stack, tile

+ ""
    + hstack(), vstack()

In [5]:
arr1 = np.ones((2, 3))
arr2 = np.ones((2, 3))

print(arr1)
print(arr2)

arr3 = np.hstack([arr1, arr2])
print(arr3)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


+ ""
    + dstack()

In [7]:
arr1 = np.ones((2, 3))
arr2 = np.ones((2, 3))

arr3 = np.dstack([arr1, arr2])
print(arr3)
print(arr3.shape)

# (2, 3, 2)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
(2, 3, 2)


In [8]:
arr1 = np.ones((3, 4))
arr2 = np.ones((3, 4))

arr3 = np.dstack([arr1, arr2])
print(arr3)
print(arr3.shape)

# (3, 4, 2)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
(3, 4, 2)


In [9]:
arr1 = [1, 2, 3]
arr2 = [4, 5, 6]

arr3 = np.dstack([arr1, arr2])
print(arr3)
print(arr3.shape)

[[[1 4]
  [2 5]
  [3 6]]]
(1, 3, 2)


In [10]:
arr1 = np.ones((3, 4))
arr2 = np.ones((3, 4))
arr3 = np.ones((3, 4))

arr4 = np.dstack([arr1, arr2, arr3])
print(arr4)
print(arr4.shape)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
(3, 4, 3)


+ ""
    + stack()

In [14]:
# axis = 0
arr1 = np.ones((3, 4))
arr2 = np.ones((3, 4))

arr3 = np.stack([arr1, arr2])
print(arr3)
print(arr3.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
(2, 3, 4)


In [15]:
# axis = 1
arr1 = np.ones((3, 4))
arr2 = np.ones((3, 4))

arr3 = np.stack([arr1, arr2], axis=1)
print(arr3)
print(arr3.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
(3, 2, 4)


In [16]:
# axis = 2, dstack과 동일
arr1 = np.ones((3, 4))
arr2 = np.ones((3, 4))

arr3 = np.stack([arr1, arr2], axis=2)
print(arr3)
print(arr3.shape)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
(3, 4, 2)


+ ""
    + tile()

In [24]:
A = 1
B = np.array([0, 1])
C = np.array([[0, 1], [2, 3]])

print(np.tile(A, 3))
print(np.tile(B, 3))
print(np.tile(C, 3))
print("--------------------------------")
print(np.tile(A, (2, 3)))
print(np.tile(B, (2, 3)))
print(np.tile(C, (2, 3)))
print("--------------------------------")
print(np.tile(B, (4, 2, 3)))

[1 1 1]
[0 1 0 1 0 1]
[[0 1 0 1 0 1]
 [2 3 2 3 2 3]]
--------------------------------
[[1 1 1]
 [1 1 1]]
[[0 1 0 1 0 1]
 [0 1 0 1 0 1]]
[[0 1 0 1 0 1]
 [2 3 2 3 2 3]
 [0 1 0 1 0 1]
 [2 3 2 3 2 3]]
--------------------------------
[[[0 1 0 1 0 1]
  [0 1 0 1 0 1]]

 [[0 1 0 1 0 1]
  [0 1 0 1 0 1]]

 [[0 1 0 1 0 1]
  [0 1 0 1 0 1]]

 [[0 1 0 1 0 1]
  [0 1 0 1 0 1]]]


## 12. BroadCasting

+ 크기가 서로 다른 행렬(백터)끼리 연산을 가능하게 하는 것

In [35]:
x = np.vstack([range(7)[i:i+3] for i in range(5)])
print(x)
print("---------------------------")
y = np.arange(5)[:, np.newaxis]
print(y)

print("---------------------------")

print(x + y)

print("---------------------------")

y = np.arange(3)
print(x + y)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
---------------------------
[[0]
 [1]
 [2]
 [3]
 [4]]
---------------------------
[[ 0  1  2]
 [ 2  3  4]
 [ 4  5  6]
 [ 6  7  8]
 [ 8  9 10]]
---------------------------
[[0 2 4]
 [1 3 5]
 [2 4 6]
 [3 5 7]
 [4 6 8]]


In [27]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [29]:
range(7)[1:1+3]

range(1, 4)

## 13. 차원 축소(Dimension reduction) 연산

+ 최대값 / 최소값 : max(), min(), argmax(), argmin()
+ 대표값 : sum(), mean(), median(), std(), var()

+ 행렬의 하나의 행에 있는 원소들을 하나의 데이터 집합으로 보고 그 집합의 평균을 구하면 각 행에 대해 하나의 숫자가 나오게 된다. 이러한 연산을 차원 축소 연산이라고 한다.

In [37]:
x = np.array([1, 3, 2, -3])

print(x.max())
print(x.min())

print("--------------------")

print(np.argmax(x)) # 최대값이 있는 곳의 인덱스
print(np.argmin(x)) # 최소값이 있는 곳의 인덱스

3
-3
--------------------
1
3


## 14. 기술 통계

+ sum(), mean()
+ var(), std()
+ max(), min()
+ median()
+ percentile()
+ ...

## 15. 정렬

In [43]:
arr = np.array([[4, 3, 5, 7],
              [1, 12, 11, 9],
              [2, 15, 1, 14]])

print(np.sort(arr))  # 기본값은 axis = 1
print("------------------------------------")
print(np.sort(arr, axis = 1))  # 행
print("------------------------------------")
print(np.sort(arr, axis = 0))  # 열

[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]
------------------------------------
[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]
------------------------------------
[[ 1  3  1  7]
 [ 2 12  5  9]
 [ 4 15 11 14]]


In [45]:
print(arr) # 원본에는 영향 없음

arr = np.sort(arr)

# 또는 
arr.sort() # 원본에 바로 정렬

print(arr)

[[ 4  3  5  7]
 [ 1 12 11  9]
 [ 2 15  1 14]]
[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]


In [48]:
######## argsort()

arr = np.array([42, 38, 12, 25])
idx = np.argsort(arr)
print(idx)

[2 3 1 0]


In [49]:
np.sort(arr)

array([12, 25, 38, 42])

In [50]:
np.sort(arr)[::-1]

array([42, 38, 25, 12])

In [51]:
arr[np.argsort(-arr)]

array([42, 38, 25, 12])

## 16. 난수

+ rand() : 0 ~ 1 사이의 균일 분포
+ randn() : 표준 정규 분포
+ randint() : 균일 분포의 정수

In [53]:
print(np.random.rand(10))
print("-------------------------")
print(np.random.rand(3, 5))

[0.37762206 0.7704584  0.64980716 0.73871019 0.82071413 0.36392384
 0.55505673 0.1907044  0.05777512 0.93392814]
-------------------------
[[0.98157812 0.42945705 0.92707305 0.86131126 0.33760285]
 [0.72377318 0.49869779 0.78481292 0.77023855 0.11405359]
 [0.88940278 0.11338552 0.41564746 0.34043302 0.42279538]]


In [58]:
print(np.random.randint(10))
print("-------------------------")
print(np.random.randint(11, 20))
print("-------------------------")
print(np.random.randint(11, 20, size = 100))
print("-------------------------")
print(np.random.randint(11, 20, size = (3, 4)))

6
-------------------------
16
-------------------------
[19 17 12 19 12 15 15 14 17 18 16 14 17 15 14 11 17 17 18 15 11 17 18 19
 14 19 15 17 15 12 11 11 19 16 18 11 12 11 13 17 17 15 14 15 13 12 15 14
 18 15 19 19 11 16 14 18 18 15 12 17 18 13 11 14 13 18 15 16 14 16 13 12
 14 18 13 19 17 18 11 17 13 16 18 18 13 17 17 14 18 16 19 18 11 18 13 19
 14 13 15 16]
-------------------------
[[19 18 19 16]
 [19 18 11 13]
 [12 13 13 17]]


In [60]:
##### 재현성(난수 고정)

print(np.random.seed(100))

print(np.random.rand(3))

None
[0.54340494 0.27836939 0.42451759]


In [61]:
##### 데이터의 순서 바꾸기

x = np.arange(10)
print(x)

np.random.shuffle(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[9 1 3 8 6 7 5 2 4 0]


In [64]:
##### 샘플링 : 복원(default), 비복원

print(np.random.choice(5, 7))
print("-----------------------------------")
print(np.random.choice(5, 5, replace=False))
print("-----------------------------------")
print(np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]))

[2 3 4 4 1 3 4]
-----------------------------------
[0 2 1 3 4]
-----------------------------------
[2 2 2 0 2 3 0 3 3 2]


## 17. 정수형 데이터 카운팅 : unique(), bincount()

In [69]:
##### unique

arr = np.array(['a', 'b', 'b', 'c', 'a'])
print(len(arr))
print(np.unique(arr))
print(len(np.unique(arr)))

print("-----------------------------------")

idx, cnt = np.unique(arr, return_counts=True)
print(idx)
print(cnt)

5
['a' 'b' 'c']
3
-----------------------------------
['a' 'b' 'c']
[2 2 1]


In [72]:
##### bincount : 발생하지 않은 사건에 대해서도 카운팅

arr = np.array([1, 1, 2, 2, 2, 3])

print(np.unique(arr, return_counts = True))
print(np.bincount(arr, minlength = 6))

(array([1, 2, 3]), array([2, 3, 1], dtype=int64))
[0 2 3 1 0 0]


## 실습문제 : 영화 평점 데이터

+ https://grouplens.org

In [76]:
data = np.loadtxt("data/ml-1m/ratings.dat", delimiter="::", dtype=np.int64)
print(data)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]


In [77]:
print(data.shape)

(1000209, 4)


In [79]:
# 첫행부터 20행까지 조회
print(data[:20])

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]
 [        1       595         5 978824268]
 [        1       938         4 978301752]
 [        1      2398         4 978302281]
 [        1      2918         4 978302124]
 [        1      1035         5 978301753]
 [        1      2791         4 978302188]
 [        1      2687         3 978824268]
 [        1      2018         4 978301777]
 [        1      3105         5 978301713]
 [        1      2797         4 978302039]]


In [88]:
# 21행부터 30행까지 userid와 movieid만 조회
print(data[20:29])

[[        1      2321         3 978302205]
 [        1       720         3 978300760]
 [        1      1270         5 978300055]
 [        1       527         5 978824195]
 [        1      2340         3 978300103]
 [        1        48         5 978824351]
 [        1      1097         4 978301953]
 [        1      1721         4 978300055]
 [        1      1545         4 978824139]]


In [ ]:
# 전체 평점에 대한 평균

In [ ]:
# 사용자 별로 평점 평균(10명만 조회)

In [ ]:
# 위의 결과 중 최고 평점 평균을 조회(userid와 함께 동시에 조회)